### PR TITLE
fix: sync error with async websocket connection initialization

### LINKED ISSUE #271: Syncing error caused by rpc client's async ws connection
When we simulate an offline environment, using `start_client()` to async connecting a web socket connection, and write some data to local storage. And then enable online to make websocket connected, the previous written data will seem to lose. (It has been stored to local storage, but is incorrect after merging in memory)

https://github.com/toeverything/OctoBase/blob/09308ede590ad370249d438cb3353afb91b9811f/libs/jwst-rpc/src/client.rs#L182

### PR DESCRIPTION
**Pull request by thorseraq**
- [x] fix collaboration bugs with async websocket connection
- [x] clean up redundant code
- [x] refactor `libs/jwst-rpc/src/bin/main.rs` to unit test

close #271

### CODE REVIEW

File: libs/jwst-rpc/src/client.rs [hunk 1]
```diff
@@ -128,6 +128,7 @@ async fn run_sync(
 
 fn start_sync_thread(workspace: &Workspace, remote: String, mut rx: Receiver<Vec<u8>>) {
     debug!("spawn sync thread");
+    println!("start_sync_thread, remote: {remote}");
```
Comment (darkskygit) [inline libs/jwst-rpc/src/client.rs:131]: useless log

File: libs/jwst-rpc/src/client.rs [hunk 2]
```diff
@@ -148,19 +149,22 @@ fn start_sync_thread(workspace: &Workspace, remote: String, mut rx: Receiver<Vec
                     remote.clone(),
                     &mut rx,
                 )
-                .await
+                    .await
                 {
                     Ok(true) => {
+                        println!("sync thread finished");
```
Comment (darkskygit) [inline libs/jwst-rpc/src/client.rs:155]: useless log

File: libs/jwst-rpc/src/client.rs [hunk 3]
```diff
@@ -148,19 +149,22 @@ fn start_sync_thread(workspace: &Workspace, remote: String, mut rx: Receiver<Vec
...
                         debug!("sync thread finished");
                         first_sync_cloned.store(true, Ordering::Release);
                         break;
                     }
                     Ok(false) => {
+                        println!("Remote sync connection disconnected, try again in 2 seconds");
```
Comment (darkskygit) [inline libs/jwst-rpc/src/client.rs:161]: useless log

File: libs/jwst-rpc/src/client.rs [hunk 4]
```diff
@@ -148,19 +149,22 @@ fn start_sync_thread(workspace: &Workspace, remote: String, mut rx: Receiver<Vec
...
                         first_sync_cloned.store(true, Ordering::Release);
                         warn!("Remote sync connection disconnected, try again in 2 seconds");
                         sleep(Duration::from_secs(3)).await;
                     }
                     Err(e) => {
+                        println!("Remote sync error, try again in 3 seconds");
```
Comment (darkskygit) [inline libs/jwst-rpc/src/client.rs:167]: useless log

File: libs/jwst-rpc/src/client.rs [hunk 5]
```diff
@@ -187,14 +191,324 @@ pub async fn start_client(
...
+            for block in blocks {
+                println!("block: {:?}", block);
+            }
+        });
+
+        fs::remove_dir_all("./data").unwrap();
+        close_collaboration_server(child);
+    }
+
+    fn create_db_dir() {
```
Comment (darkskygit) [inline libs/jwst-rpc/src/client.rs:433]: consider using the `tempfile` crate

**Review by darkskygit — APPROVED** [review]

**Review by darkskygit — APPROVED** [review]
